{{ if and (eq .Values.provider "jaeger") (eq .Values.jaeger.template "production-elasticsearch") }}
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "jaeger"
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  strategy: production

  query:
    {{- if and .Values.jaeger.hub .Values.jaeger.tag }}
    image: {{ .Values.jaeger.hub }}/jaeger-query:{{ .Values.jaeger.tag }}
    {{- end }}
    options:
      query:
        base-path: /
    annotations:
      {{- range $key, $value := .Values.jaeger.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}

  collector:
    {{- if and .Values.jaeger.hub .Values.jaeger.tag }}
    image: {{ .Values.jaeger.hub }}/jaeger-collector:{{ .Values.jaeger.tag }}
    {{- end }}
    annotations:
      {{- range $key, $value := .Values.jaeger.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}

  agent:
    options:
      collector:
        host-port: jaeger-collector:14267
    annotations:
      {{- range $key, $value := .Values.jaeger.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}

  ui:
    options:
      dependencies:
        menuEnabled: false
      menu:
        - label: "About Jaeger"
          items:
            - label: "Documentation"
              url: "https://www.jaegertracing.io/docs/latest"
            - label: "Log Out"
              url: "/oauth/sign_in"
              anchorTarget: "_self"

  storage:
    type: elasticsearch
    elasticsearch:
{{- if .Values.jaeger.elasticsearch.nodeCount }}
      nodeCount: {{ toYaml .Values.jaeger.elasticsearch.nodeCount }}
{{- else }}
      nodeCount: 3
{{- end }}
{{- if .Values.jaeger.elasticsearch.storage }}
      storage:
{{ toYaml .Values.jaeger.elasticsearch.storage | indent 8 }}
{{- end }}
{{- if .Values.jaeger.elasticsearch.redundancyPolicy }}
      redundancyPolicy: {{ toYaml .Values.jaeger.elasticsearch.redundancyPolicy }}
{{- end }}
      nodeSelector:
        {{- range $key, $value := .Values.jaeger.elasticsearch.nodeSelector }}
          {{ $key }}: {{ $value | quote }}
        {{- end }}
      resources:
{{- if .Values.jaeger.elasticsearch.resources }}
{{ toYaml .Values.jaeger.elasticsearch.resources | indent 8 }}
{{- else }}
        requests:
          memory: "16Gi"
          cpu: "1"
        limits:
          memory: "16Gi"
{{- end }}

  ingress:
    enabled: {{ .Values.ingress.enabled }}
    # XXX: should this be parameterized?
    security: oauth-proxy
    annotations:
      {{- range $key, $value := .Values.ingress.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    openshift:
      sar: '{"namespace": "{{ .Release.Namespace }}", "resource": "pods", "verb": "get"}'
      htpasswdFile: /etc/proxy/htpasswd/auth

  volumeMounts:
  - name: secret-htpasswd
    mountPath: /etc/proxy/htpasswd
  volumes:
  - name: secret-htpasswd
    secret:
      secretName: htpasswd
  resources:
{{- if .Values.jaeger.resources }}
{{ toYaml .Values.jaeger.resources | indent 4 }}
{{- else }}
{{ toYaml .Values.global.defaultResources | indent 4 }}
{{- end }}
  affinity:
  {{- include "nodeaffinity" . | indent 2 }}

{{ end }}
